//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWS_API_EF.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class tbl_Payments
    {
        public int Id_Payment { get; set; }
        public int Id_Client_Payment { get; set; }
        public int Id_WorkOrder_Payment { get; set; }
        public System.DateTime Date_Payment { get; set; }
        public decimal Amount_Payment { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tbl_Clients tbl_Clients { get; set; }
        
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual tbl_WorkOrders tbl_WorkOrders { get; set; }
    }
}
