//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWS_API_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Users
    {
        public int Id_User { get; set; }
        public string Name_User { get; set; }
        public string NickName_User { get; set; }
        public string Password_User { get; set; }
        public bool AdminRights_User { get; set; }
    }
}
